//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public Nullable<byte> User_PostType_Id { get; set; }
        public Nullable<byte> User_SecurityQuestion_Id { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public string UserMobileNumber { get; set; }
        public string UserEmail { get; set; }
        public string UserAnswer { get; set; }
        public string UserRegistrationDate { get; set; }
        public string UserImage { get; set; }
        public string UserDescription { get; set; }
    }
}
