//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewDoctor
    {
        public int Id { get; set; }
        public Nullable<short> Specialty_Id { get; set; }
        public Nullable<short> County_Id { get; set; }
        public string Doctor_Id { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string MobileNumber { get; set; }
        public string Description { get; set; }
        public string SpecialtyName { get; set; }
        public string CountyName { get; set; }
        public string ProvinceName { get; set; }
        public short Province_Id { get; set; }
    }
}
