//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbVisitorEntities : DbContext
    {
        public dbVisitorEntities()
            : base("name=dbVisitorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCounty> tblCounty { get; set; }
        public virtual DbSet<tblDoctor> tblDoctor { get; set; }
        public virtual DbSet<tblDoctorPatient> tblDoctorPatient { get; set; }
        public virtual DbSet<tblLicense> tblLicense { get; set; }
        public virtual DbSet<tblPatient> tblPatient { get; set; }
        public virtual DbSet<tblPostType> tblPostType { get; set; }
        public virtual DbSet<tblProvince> tblProvince { get; set; }
        public virtual DbSet<tblSecurityAccess> tblSecurityAccess { get; set; }
        public virtual DbSet<tblSecurityQuestion> tblSecurityQuestion { get; set; }
        public virtual DbSet<tblSpecialty> tblSpecialty { get; set; }
        public virtual DbSet<tblSundry> tblSundry { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblVisitDoctor> tblVisitDoctor { get; set; }
        public virtual DbSet<viewDoctor> viewDoctor { get; set; }
        public virtual DbSet<viewDoctorPatient> viewDoctorPatient { get; set; }
    
        public virtual ObjectResult<Nullable<int>> spAutoDoctorId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spAutoDoctorId");
        }
    
        public virtual ObjectResult<Nullable<int>> spAutoPatientId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spAutoPatientId");
        }
    
        public virtual ObjectResult<spSelectViewDoctor_Result> spSelectViewDoctor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectViewDoctor_Result>("spSelectViewDoctor");
        }
    
        public virtual ObjectResult<spSelectViewDoctorPatient_Result> spSelectViewDoctorPatient()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSelectViewDoctorPatient_Result>("spSelectViewDoctorPatient");
        }
    }
}
